config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :discussions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :posts, only: [:create, :show, :edit, :update, :destroy], module: :discussions

    collection do
      get 'category/:id', to: "categories/discussions#index", as: :category
    end
  end
  root to: "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true

  validates :name, presence: true

  has_many :posts, dependent: :destroy

  accepts_nested_attributes_for :posts


  # discussion.category_name
  delegate :name, prefix: :category, to: :category, allow_nil: true

  broadcasts_to :category, inserts_by: :prepend


  after_create_commit -> { broadcast_prepend_to "discussions" }
  after_update_commit -> { broadcast_replace_to "discussions" }
  after_destroy_commit -> { broadcast_remove_to "discussions" }

  def to_param
    "#{id}-#{name.downcase.to_s[0...100]}".parameterize
  end
end

app/controllers/categories/discussions_controller.rb
module Categories
    class DiscussionsController < ApplicationController
      before_action :authenticate_user!
      before_action :set_category
  
      def index
        @discussions = @category.discussions.order(updated_at: :desc)
        render 'discussions/index'
      end
  
      private
  
      def set_category
        @category = Category.find(params[:id])
      end
    end
  end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion, notice: "Post update" }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to discussion_path(@discussion), notice: "Post created" }
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy

      respond_to do |format|
        format.turbo_stream { } # let the callback delete the post
        format.html { redirect_to @post.discussion, notice: "Post deleted" }
      end
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body)
    end
  end
end

 

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: [:show, :edit, :destroy, :update]

  def index
    @discussions = Discussion.all.order(updated_at: :desc)
  end

  def show
    @posts = @discussion.posts.all.order(created_at: :asc)
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Discussion created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        @discussion.broadcast_replace(partial: "discussions/header", locals: { discussion: @discussion })

        format.html { redirect_to @discussion, notice: "Discussion updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discussion.destroy!
    redirect_to discussions_path, notice: 'Discussion removed'
  end

  private

  def discussion_params
    params.require(:discussion).permit(:name, :category_id, :closed, :pinned, posts_attributes: :body)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/views/discussions/_discussion.html.erb
<div id="<%= dom_id(discussion) %>" class="mb-2">
  <h2><%= link_to discussion.name, discussion %></h2>
 | Closed: <%= discussion.closed %><br />
  Posted in: <%= discussion.category_name %> | Posts: <%= discussion.posts_count %>
  <div>
    <%= link_to "Edit", edit_discussion_path(discussion) %> |
    <%= link_to "Delete", discussion, method: :delete, data: { confirm: "Are you sure? This cannot be undone" } %>
  </div>
</div>

app/views/discussions/_form.html.erb
<%= form_with(model: discussion) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prevented this discussion from being saved:</h2>
      <ul>
        <% discussion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, placeholder: "How do I...?", class: "form-control" %>
  </div>

  
  <div class="mb-3">
    <%= form.label :category_id, "Choose a category", class: "form-label" %>
    <%= form.collection_select :category_id, Category.sorted, :id, :name,
      { include_blank: "Pick a category..." },
      { autofocus: false, class: "form-control" } %>
  </div>


  <div class="mb-3">
    <%= form.label :closed, class: "form-label" %>
    <%= form.check_box :closed %>
  </div>

  <% if discussion.new_record? %>
    <%= form.fields_for :posts do |p| %>
      <div class="mb-3">
        <%= p.rich_text_area :body, placeholder: "Kickoff the discussion" %>
      </div>
    <% end %>
  <% end %>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/discussions/_header.html.erb
<%= turbo_frame_tag dom_id(discussion) do %>
  <div class="d-flex align-items-center justify-content-between">
    <div>
      <h1><%= discussion.name %></h1>
      <span class="text-muted fs-6">
        <% if discussion.closed %>
          <span class="badge rounded-pill text-danger">Closed</span>
        <% end %>
      </span>
    </div>
    <div>
      <%= link_to "Edit", edit_discussion_path(discussion) %> |
      <%= link_to "Destroy", discussion, method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h1>Edit discussion</h1>
<%= turbo_frame_tag dom_id(@discussion) do %>
  <%= render("form", discussion: @discussion) %>
  <%= link_to "Cancel", @discussion %>
<% end %>

app/views/discussions/index.html.erb
<% if @category.present? %>
  <%= turbo_stream_from @category %>
<% else %>
  <%= turbo_stream_from 'discussions' %>
<% end %>

<div class="d-flex justify-content-between align-items-center">
  <h1>Discussions</h1>
  <%= link_to "New discussion", new_discussion_path, class: "btn btn-primary" %>
</div>

<div class="row mt-4">
  <div class="col-3">
    <%= turbo_stream_from 'categories' %>
    <h5>Categories</h5>
    <div id="categories">
      <%= render(partial: "categories/category", collection: Category.sorted) %>
    </div>
  </div>

  <div class="col">
    <% if @category %>
      <h4>Viewing discussions in <%= @category.name %></h4>
    <% end %>
    <div id="discussions">
      <%= render partial: "discussions/discussion", collection: @discussions %>
    </div>
  </div>
</div>

app/views/discussions/new.html.erb
<h1>New Discussion</h1>

<%= render("form", discussion: @discussion) %>

app/views/discussions/show.html.erb
<%= turbo_stream_from @discussion %>
<%= render(partial: "discussions/header", locals: { discussion: @discussion }) %>

<div id="posts"class="mt-4">
  <%= render partial: "discussions/posts/post", collection: @posts %>
</div>

<hr class="my-4">

<div id="<%= dom_id(@new_post) %>">
  <%= render("discussions/posts/form", post: @new_post) %>
</div>