config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :discussions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :posts, only: [:create, :show, :edit, :update, :destroy], module: :discussions

    collection do
      get 'category/:id', to: "categories/discussions#index", as: :category
    end
  end
  root to: "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :user, default: -> { Current.user }
  belongs_to :category, counter_cache: true, touch: true

  validates :name, presence: true

  has_many :posts, dependent: :destroy

  accepts_nested_attributes_for :posts


  # discussion.category_name
  delegate :name, prefix: :category, to: :category, allow_nil: true

  broadcasts_to :category, inserts_by: :prepend


  after_create_commit -> { broadcast_prepend_to "discussions" }
  after_update_commit -> { broadcast_replace_to "discussions" }
  after_destroy_commit -> { broadcast_remove_to "discussions" }

  def to_param
    "#{id}-#{name.downcase.to_s[0...100]}".parameterize
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :discussion, counter_cache: true, touch: true
  belongs_to :user, default: -> { Current.user }

  has_rich_text :body

  validates :body, presence: true

  after_create_commit -> { broadcast_append_to discussion, partial: "discussions/posts/post", locals: { post: self }}
  after_update_commit -> { broadcast_replace_to discussion, partial: "discussions/posts/post", locals: { post: self }}
  after_destroy_commit -> { broadcast_remove_to discussion }
end

app/controllers/categories/discussions_controller.rb
module Categories
    class DiscussionsController < ApplicationController
      before_action :authenticate_user!
      before_action :set_category
  
      def index
        @discussions = @category.discussions.order(updated_at: :desc)
        render 'discussions/index'
      end
  
      private
  
      def set_category
        @category = Category.find(params[:id])
      end
    end
  end

app/controllers/discussions/posts_controller.rb
module Discussions
  class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_discussion
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def show
    end

    def edit
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post.discussion, notice: "Post update" }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def create
      @post = @discussion.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to discussion_path(@discussion), notice: "Post created" }
        else
          format.turbo_stream
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @post.destroy

      respond_to do |format|
        format.turbo_stream { } # let the callback delete the post
        format.html { redirect_to @post.discussion, notice: "Post deleted" }
      end
    end

    private

    def set_discussion
      @discussion = Discussion.find(params[:discussion_id])
    end

    def set_post
      @post = @discussion.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:body)
    end
  end
end

 

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_discussion, only: [:show, :edit, :destroy, :update]

  def index
    @discussions = Discussion.all.order(updated_at: :desc)
  end

  def show
    @posts = @discussion.posts.all.order(created_at: :asc)
    @new_post = @discussion.posts.new
  end

  def new
    @discussion = Discussion.new
    @discussion.posts.new
  end

  def create
    @discussion = Discussion.new(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Discussion created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        @discussion.broadcast_replace(partial: "discussions/header", locals: { discussion: @discussion })

        format.html { redirect_to @discussion, notice: "Discussion updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @discussion.destroy!
    redirect_to discussions_path, notice: 'Discussion removed'
  end

  private

  def discussion_params
    params.require(:discussion).permit(:name, :category_id, :closed, :pinned, posts_attributes: :body)
  end

  def set_discussion
    @discussion = Discussion.find(params[:id])
  end
end

app/views/discussions/posts/_form.html.erb
<%= turbo_frame_tag "#{dom_id(post)}_form", target: "_top" do %>
  <%= form_with(model: [post.discussion, post]) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explantion">
        <h2>
          <%= pluralize(post.errors.count, "error") %>
          prohibited this post from being saved:
        </h2>
        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :body, class: "visually-hidden form-label" %>
      <%= form.rich_text_area :body, placeholder: "Add your comment", autofocus: true %>
    </div>

    <div class="mb-3">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/discussions/posts/_header.html.erb
<h6 class="card-subtitle mb-3 text-muted border-bottom pb-3">Posted on: <%= post.created_at %></h6>

app/views/discussions/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div class="card my-4">
    <div class="card-body">
      <%= render(partial: "discussions/posts/header", locals: { post: post }) %>
      <%= post.body %>
    </div>

    <div class="card-footer">
      <%= link_to "Edit", edit_discussion_post_path(post.discussion, post), data: { turbo_frame: dom_id(post) } %> |
      <%= link_to "Delete", discussion_post_path(post.discussion, post), method: :delete %>
    </div>
  </div>
<% end %>

app/views/discussions/posts/create.turbo_stream.erb
<%= turbo_stream.replace "new_post_form" do %>
  <%= render partial: "discussions/posts/form", formats: :html, locals: { post: @post } %>
<% end %>

app/views/discussions/posts/edit.html.erb
<h1>Edit post</h1>
<%= turbo_frame_tag dom_id(@post) do %>
  <div class="card my-4">
    <div class="card-body">
      <%= render(partial: "discussions/posts/header", locals: { post: @post }) %>
      <%= render("form", post: @post) %>
      <%= link_to 'Back', discussion_post_path(@post.discussion, @post) %>
    </div>
  </div>
<% end %>

app/views/discussions/posts/show.html.erb
<%= render partial: "discussions/posts/post", locals: { post: @post } %>