config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :discussions, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :posts, only: [:create, :show, :edit, :update, :destroy], module: :discussions

    collection do
      get 'category/:id', to: "categories/discussions#index", as: :category
    end
  end
  root to: "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Hotwire Forums", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to "Discussions", discussions_path, class: "nav-item nav-link" %>
        <%= link_to "Categories", categories_path, class: "nav-item nav-link" %>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to Current.user.email, edit_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>